---
title: 'The psychology of managerial risky choice and resource allocation'
author: 'Shir Dekel'
date: '`r format(Sys.time())`'
institution: 'The University of Sydney'
# division: 'School of Psychology'
# advisor: 'Micah Goldwater'
department: 'Faculty of Science'
degree: 'Doctor of Philosophy (Science)'
knit: bookdown::render_book
site: bookdown::bookdown_site

output:
  thesisdown::thesis_pdf: default 
  thesisdown::thesis_word: default

abstract: (ref:abstract)
# acknowledgements: |
#   Acknowledgements.
# dedication: |
#   Dedication. 
# preface: |
#   Preface.
  
bibliography: inst/references.bib
csl: inst/apa.csl
# lot: true
# lof: true
---

```{r setup, include=FALSE}
library(drake)
library(tidyverse)
library(magick)
library(here)
library(knitr)

loadd(starts_with("descriptives"))
loadd(starts_with("results"))
loadd(starts_with("plot"))
loadd(starts_with("gambles"))

opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  out.width = "100%"
)
```

(ref:abstract) People often have to make decisions in situations in which they
have both semantically and statistically relevant information. The literature
suggests that people are often influenced by largely semantic (and sometimes
irrelevant) information despite the availability of useful statistical
information. Further, it is likely that these kinds of biases are just as, if
not more, common for people in management roles. The thesis is that people tend
to treat risky choices one at a time, are influenced by set similarity when they
are forced to consider them together, and have to rely on anecdotes when the set
is dissimilar. I explored this thesis through three specific research
questions. 1. How does choice grouping affect people's repeated risky choices
when not presented with immediate feedback? I found that people accept more
risky choices when they are presented as an aggregated distribution, rather than
separately. 2. How does option similarity and variance information affect
resource allocation behaviour? I found that when options are similar people are
able to selectively respond to reliability information about given data, whereas
when options are dissimilar people have to rely on an easily comparable metric,
regardless of its reliability. However, people struggled to use reliability
information to make these decisions when it was expressed as numerical ranges,
rather than as words. 3. How do anecdotes, and their similarity to the problem
at hand, affect resource allocation. I found that anecdote similarity
strengthens the effect of anecdotes, and that even explicit hints do not reduce
the anecdote effect. These results have implications both for how people make
decisions, and how managers in large organisations may be biased when making
important decisions. First, they suggest that people struggle to appreciate the
value of risk aggregation when they consider individual risky choices in
isolation. Second, when choices are presented jointly, people are affected by
choice similarity and struggle to use numerical variance information in their
decisions. Third, people show a bias towards using anecdotes over aggregated
data, but moderate this preference based on anecdote relevance.
