## General discussion

I found that choice bracketing facilitated risk aggregation in
description-based repeated-play gambles. This paradigm has never been a target
of research. Early work on risk aggregation involved multi-play gambles, which
treated gambles as simultaneous and identical. However, most risky choice
outside the lab involves considering multiple choices independently, as in
repeated-play paradigms. Most repeated-play paradigms have involved providing
participants with feedback, or allowing them to sample from outcome
distributions. Large real-life investments are different, as their outcomes are
not eventuated immediately (and do not allow for distribution sampling). The
limited prior work using description-based repeated-play gambles did not
consider the effect of choice bracketing on risk aggregation. As such, my
paradigm allowed for the investigation of choice bracketing in a way that is
isomorphic with real-life prescriptions.

In addition to the novelty of the paradigm itself, I found that choice
bracketing facilitates risk aggregation. As per Hypothesis 1, I found that
merely knowing that further choices will have to be made reduces risk aversion.
As per Hypothesis 2, I found that people are less risk averse when viewing
their choices together. Contrary to Hypothesis 3, I did not find a main effect
of similarity, but instead found that similarity moderated the presentation
effect. That is, joint presentation is not as useful if projects cannot be
easily compared. Unsurprisingly, as per Hypothesis 4, I found that risk
aversion was further reduced when a distribution of outcome probabilities was
provided. Altogether, it seems that although subtle contextual cues were able to
encourage risk aggregation, people still struggled to aggregate as much as when
risk is aggregated for them.

my choice bracketing findings are largely congruent with, but extend, previous
research. @sokolhessner2009 and @sokolhessner2012 found that encouraging
participants to make decisions akin to a professional investor increased the
amount of risky choices they made. I found that risky choice increased with an
even subtler manipulation: whether or not participants were aware of the number
of choices to be made. @hsee1999 found that useful, but hard-to-interpret,
attributes were used more when the options were presented jointly, rather than
separately. In my case, the "hard to interpret" element of the decision set was
the risk of the projects. Similar to @hsee1999, it seemed that risk was
accounted for more when projects were presented jointly, rather than separately.

Research on the effect of option similarity on choice [e.g., @markman1995]
suggests that alignable differences are more important than non-alignable
differences. Further, the effects of multi-play gambles and outcome
distributions on risk aggregation are only seen when participants perceive the
options as fungible [e.g., @dekay2005]. As such, I predicted that a set of
investments that involve the same type of investment would be seen as more
similar and fungible. I expected that this would facilitate a broad bracketing,
and therefore more risk aggregation.

While I did not find a main effect of similarity, I found that choice
similarity interacted with the presentation condition. I are unable to clearly
account for this effect, since I would have expected to see it in the opposite
direction. That is, I would have expected that seeing a set of similar projects
would help participants aggregate risk when seeing them separately, more than
when projects are dissimilar. Note, however, that there was no significant
difference between similarity conditions when viewing projects separately. As
such, the effect can be interpreted as having benefited from a joint
presentation more when projects were all from the same industry than when they
were from different industries. Perhaps the ability to aggregate risk when
projects are presented together is more made more salient when projects are
similar.Future research should investigate this effect further.

my finding that participants are less risk averse when provided with an
aggregated outcome distribution is also congruent with previous work [e.g.,
@redelmeier1992]. However, when distributions have been previously used, gambles
were identical in multi-play paradigms and used immediate feedback for
repeated-play paradigms [e.g., @benartzi1999]. As I mentioned previously, both
these paradigms have limited ecological validity because usually people are
faced with non-identical sequential choices and do not receive immediate
feedback. I are the first to provide evidence for this aggregation effect with
non-identical gambles without feedback .

Limitations of cognitive capacity might explain some of these choice bracketing
effects [@read1999]. People appear to have a bounded rationality that is not
perfectly congruent with principles of economics such as EV theory [e.g.,
@simon1955; @kahneman2003]. However, people's decisions that can be considered
irrational or non-optimal are often subsequently amended when aided [e.g.,
@schkade1994]. As such, the finding that participants aggregate risk more when
provided with an aggregated outcome probability distribution is not particularly
surprising; the bottleneck of mentally aggregating the risk is removed, such
that all that is left is the participants' risk preference.

However, it is unlikely that the participants became better mathematicians due
to my choice bracketing manipulation. Instead, choice bracketing during the
repeated-play gambles may be encouraging a more naive risk aggregation. That is,
participants may be becoming more risk tolerant because choice bracketing, such
as the joint presentation, reinforces the existence of other risky options.
Perhaps the possibility of recouped losses become more salient when other
projects are made more salient.

This research implies some prescriptions for resource allocation
decision-making. For instance, managers can implement processes that encourage a
joint evaluation of projects. This way projects can be considered as individual
components in a portfolio, thereby facilitating better risk aggregation. Some
companies are already implementing such processes [@lovallo2020]. When that is
not possible and projects must still be evaluated sequentially, my research
suggests that making the existence of other projects salient will encourage risk
aggregation. For example, executives can use simple reminders that ask how many
future risky projects will be evaluated in a given time frame.

Interestingly, participants were able to take advantage of the joint, compared
to the separate, presentation more when the projects were all from the same
industry than when industries differed. Simply manipulating the similarity of
financially-irrelevant semantics of a set of choices affected participants' risk
aversion. This has implications for managerial settings. Executives in
multi-business firms often have to make resource allocation decisions that
involve comparing dissimilar projects. How can an oil well exploration project
be appropriately compared to an oil refinery? Or to a microchip project?
Previous research suggests that evaluating dissimilar business projects is more
difficult to comparing similar projects [@dekel2019]. The current work suggests
that the gains of joint comparison would be amplified, compared to separate
evaluation, when comparing a set of similar projects.

One potential limitation of my experiment is that I provided participants with
explicit probabilities for gamble outcomes. However, in real-life decisions
people rarely have specific probability information when evaluating risky
choices. More often, people tend to make decisions under *ambiguity*, meaning
that the outcome probabilities themselves are uncertain [@curley1986]. Both lay
people and managers show *ambiguity aversion*, preferring risky gambles (in
which probabilities are certain) to ambiguous gambles [in which probabilities
are uncertain; @curley1986; @keren1999; @ho2002; @viscusi1999]. As such, it is
unclear whether my results will also be seen in a paradigm with ambiguous
choices. However, @fox1995 only found ambiguity aversion in a within-subjects
experiment and not in a between-subjects experiment. That is, participants did
not treat risky and ambiguous choices differently when the two types of choices
were not available for comparison. This finding suggests that there may not be a
difference in the effects I found in a real-life ambiguous choice environment.
Further, @liu2009 found that playing ambiguous gambles as multi-play gambles
inhibited ambiguity aversion. As such, it is unlikely that a paradigm with
ambiguous choices would find different results to the current study. Future
research should investigate this further.

# The relationship between diversification and aggregation

A diversified portfolio is one whose investments are uncorrelated or negatively
correlated. According to Portfolio Theory [@markowitz1952], a diversified
portfolio is preferred to one that is not diversified, because it reduces the
probability of a loss. When some investments have losses, others will have
gains; the root of "don't keep all your eggs in one basket." Aggregating a
portfolio of investments means to combine their outcomes and corresponding
probabilities into one decision (that is essentially just an outcome probability
distribution). This works because the aggregated risk is lower than any
individual investment risk. See @kahneman1993 for illustrative examples.

Typically, questions of gamble aggregation assume that each gamble is
independent. That is, the gambles are uncorrelated. As such, in a way,
aggregation of a portfolio already assumes that the portfolio is somewhat
diversified (at least that the gambles aren't perfectly correlated).

# How does choice bracketing facilitate aggregation

The literature suggests that multi-play effects (with and without a distributions) are due to the way that people weigh losses. The mechanism for repeated-play effects from experience is unclear.

## Multi-play

Much of the literature [e.g., @benartzi1999] is not clear about why they think
choice bracketing occurs. Some explain the effect of bracketing on aggregation
using risk aversion [e.g., @read1999], while others refer to the increased
weighting of potential losses [@webb2017].

## Repeated-play

Decision-from-experience *sampling* studies explain the underweighting of rare
events (as opposed to the overweighting that occurs with
decisions-from-description) by sampling bias and recency effects [e.g.,
@hertwig2004; @wulff2018]. That is, they explain that people are less risk
averse for positive EV gambles because when they sample from the distribution
they only sample a small amount (usually approximately 20 times) so they do not experience
rare events very often. Also, the latter half of the sequence of sampling is
significantly more predictive than the former (recency effect). Some
decision-from-experience *feedback* studies explain this effect by "choice
inertia" [@camilleri2011]. That is, "the tendency to repeat the last choice,
irrespective of the obtained outcome" (p. 383). However, there is not much more
elaboration beyond this. Repeated-play gambles show more underweighting than
multi-play gambles. This is said to be due to a "reliance on a very small set of
samples" [@camilleri2013, p. 64]. However, this explanation does not account
for repeated-play effects independently.

One way of addressing the question of whether people are aggregating naively or not is to pose participants a set of negative EV gambles.
However, that would require mixed gambles.
That is, a gamble with one risky (10% of winning 25 and 90% of losing 10) option and one certain (lose 20) option.
