---
title: "Future ARC proposal: Improving risky choice in business innovation"
author: "Bruce Burns, Shir Dekel, Micah Goldwater, Dan Lovallo"
date: "`r Sys.Date()`"
output: 
  powerpoint_presentation:
    reference_doc: template.pptx
---

## Aims and hypotheses
- Aim: to help Australian organisations overcome risk aversion
- Project 1: Risk aggregation
    - Hypothesis 1: showing managers a distribution of choice outcomes will
      reduce risk aversion.
    - Hypothesis 2: interventions that encourage managers to bracket projects
      together will reduce risk aversion.
- Project 2: Project similarity and metric variance
    - Hypothesis 1: dissimilar project comparisons will lead to an over-reliance
      on coarse financial metrics when making resource allocation decisions.
    - Hypothesis 2: managers will only use variability information to inform
      their decisions after explicit intervention.
- Project 3: Case study similarity
    - Hypothesis 1: business project case studies will influence allocation
    decisions even when aggregated data is available.
    - Hypothesis 2: case study similarity will strengthen the case study effect
      
## Impact

- Project 1
    - Improve returns for Australian businesses by leveraging the power
      of risk aggregation.
- Project 2
    - Increase the ease and precision of business project comparisons
      for Australian executives in diversified firms.
- Project 3
    - Reduce executives' reliance on uninformative case studies when
      aggregated data is available.
