## Experiment 1

```{r setup-aggregation-1}
loadd(descriptives_aggregation_1)
loadd(results_aggregation_1)
loadd(plot_aggregation_1)
loadd(gambles_aggregation_1)
```

In Experiment 1, I investigated the effect of three choice bracketing
manipulations on risky choice in hypothetical resource allocation scenarios.
Previous research had low ecological validity because of the use of multi-play
paradigms or feedback. In this experiment, the risky choice task was a
description-based repeated-play paradigm, meaning that participants had to make
a choice about whether to accept a number of different hypothetical investments,
but were not provided with feedback about their choices. I manipulated the
similarity of the choices, whether they were presented together or separately,
and whether participants were aware of the number of choices they would be
making.

The values and probabilities of the gambles were set up such that each
individual gamble, as well as the aggregation of all the gambles, would be
attractive to a "rational agent" interested in maximizing EV. As such, the key
dependent measure was the proportion of risky choices participants accept.
Following the series of choices, I presented participants an outcome
probability distribution as in the previous literature [e.g., @redelmeier1992;
@webb2017] to determine their risk aversion when the gambles are explicitly
aggregated. Note that in the past work, participants were shown ordinary
binomial distributions, since multi-play gambles are identical. To our
knowledge, there has not been an investigation of *non-identical* gamble
distributions in this context. Doing this requires using a *Poisson* binomial
distribution, which allows for multiple trials with different probabilities.

Previous research suggests that people will exhibit more risky choice when
explicitly told to bracket their choices [@sokolhessner2009; @sokolhessner2012],
when choices are presented jointly [e.g., @moher2010; @hsee1999], and when
choices are similar [e.g., @dekay2005; @markman1995]. Further, multi-play
gambles with outcome distributions have been shown to reduce risk aversion
compared to multi-play gambles without distributions [e.g., @redelmeier1992;
@webb2017]. Therefore, I tested the following hypotheses:

1. Participants that know how many projects to expect will make more risky
   choices than participants that are unaware.

2. Participants will make more risky choices when seeing projects jointly than
   when seeing them separately.

3. Participants that see projects from the same industry will make more risky
   choices than participants that see projects from different industries.

4. Participants will make more risky choices when presented with an aggregated
   outcome distribution than when making the same decisions individually.
