---
title             : "Alignment Experiment 8 - Results summary"
shorttitle        : ""

note              : Created `r format(Sys.time())`

author: 
  - name          : "Shir Dekel"
  
floatsintext      : yes

bibliography      : '`r system.file("refs.bib", package = "shiR")`'
csl               : '`r system.file("apa.csl", package = "shiR")`'
documentclass     : "apa7"
classoption       : "man, donotrepeattitle"
output: 
  papaja::apa6_pdf:
    includes: 
      in_header: "preamble.tex"
---

```{r setup, include = FALSE}
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
loadd(descriptives_alignment_8)
loadd(results_alignment_8)
loadd(plot_alignment_8)
```

# Participants

`r descriptives_alignment_8$apa` Table\ \@ref(tab:condition-allocation-table) shows the condition allocation.

```{r condition-allocation-table}
descriptives_alignment_8$condition_allocation_table %>% 
  apa_table("Group allocation to the between-subject variables of awareness, presentation, and distribution.")
```

# Results

## Project allocation

Figure\ \@ref(fig:plot-allocation) shows the allocation data. Table\ \@ref(tab:allocation-results)

```{r plot-allocation, fig.cap = "Mean project acceptance for the similarity effect."}
plot_alignment_8
```


```{r allocation-results, fig.cap = "lmer output."}
results_alignment_8$table %>%
  apa_table()
```
